### ISSUE TITLE
add "Former Staff" page/section

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#100]
Add a page or section where former staff can be listed.

**Comment by bamelegari** [comment]
Current idea: change prior employees' summaries to a generic (or not so much) message informing users that they have moved on. They are already hidden in the staff list if you change the "status" bit to 0 in the database.

**Comment by bamelegari** [comment]
The recent commit adds a drop-down accordion (similar to those on the data page: http://www.snap.uaf.edu/data.php) that contains similar thumbnails for all former employees. If anyone has any problems or suggestions, they are welcome.

**Comment by brucecrevensten** [comment]
Let us know when this is ready for some review on testing site, Bryce.
 And/or some code-check, I'd be glad to do.

On Wed, Oct 9, 2013 at 4:08 PM, bamelegari notifications@github.com wrote:

> The recent commit adds a drop-down accordion (similar to those on the data
> page: http://www.snap.uaf.edu/data.php) that contains similar thumbnails
> for all former employees. If anyone has any problems or suggestions, they
> are welcome.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/100#issuecomment-26019745
> .

## 

_Bruce Crevensten_
*
*
*Senior Software Engineer
*
(SNAP) Scenarios Network for Alaska & Arctic Planning
www.snap.uaf.edu

_Engineering Coordinator_
(ACUASI) Alaska Center for Unmanned Aerial Systems Integration

**Comment by bamelegari** [comment]
summary of changes:
*added drop-down accordion to people page containing former staff
*added line of (currently red) text to the individual people page of former employees stating that they are no longer employed with SNAP
*individual people pages now only display non-email contact info if that staff member is currently employed.
    (ie phone and fax numbers will be hidden for people who are no longer staff)
