### ISSUE TITLE
Post S. Mcafee's paper on the site 

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#101]
per request for new content:

Hi Bruce,  

I do have a new paper out in GRL as of late August: "Influence of bias correction on simulated landcover changes"
http://www.agu.org/pubs/crossref/2012/2012GL052808.shtml

Thanks,
Steph

**Comment by bamelegari** [comment]
Would it be possible to get some more information on this? ie when entering in the db there's bools for accap, snap and fsc (not sure which ones apply). Also, is there specific text that should go in the summary?

**Comment by brucecrevensten** [comment]
ensure the 'snap' field is checked, the others are not used.

Email Stephanie and ask her what she'd like.

On Mon, Mar 11, 2013 at 3:53 PM, bamelegari notifications@github.comwrote:

> Would it be possible to get some more information on this? ie when
> entering in the db there's bools for accap, snap and fsc (not sure which
> ones apply). Also, is there specific text that should go in the summary?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/101#issuecomment-14750658
> .

## 

*Bruce Crevensten, Programmer
*
(ACUASI) Alaska Center for UAS Integration
(SNAP) Scenarios Network for Alaska & Arctic Planning
www.snap.uaf.edu
