### ISSUE TITLE
Chart has leftmost text cut off (rare)

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#105]
Some pixels are missing from the label on the left side of the screen here:

http://www.snap.uaf.edu/charts.php#community=2184&dataset=2&scenario=a1b&variability=0

This doesn't look widespread or new, I can recreate it on production/test/local.  Haven't seen it before.

**Comment by bamelegari** [comment]
Is this still an issue? Just wondering if the chart purging implemented in issue #136 fixed this as well

**Comment by brucecrevensten** [comment]
Not issue on new site.
