### ISSUE TITLE
Update Community Charts photo on home page

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#114]
Look changed in v1.2.0, update

**Comment by takurkowski** [comment]
![snap_chart_kivalina_alaska_temperature_a1b_lowres](https://f.cloud.github.com/assets/1444284/772174/32a3a14e-e8fe-11e2-9a7f-d0a9ebea05c0.png)

**Comment by brucecrevensten** [comment]
Merged into master.
