### ISSUE TITLE
possibly a CRUTS31 warning in the wrong spot?

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#117]
http://www.snap.uaf.edu/data.php#dataset=historical_derived_temperature_2km

^ I don't think that one should be there.

**Comment by takurkowski** [comment]
Nope, it should not.

Tom

**Comment by brucecrevensten** [comment]
hack-fixed on production server, will leave ticket open until resolved in
source code.

On Fri, Nov 30, 2012 at 8:43 PM, Tom Kurkowski notifications@github.comwrote:

> Nope, it should not.
> 
> Tom
> On Nov 30, 2012 8:40 PM, "Bruce Crevensten" notifications@github.com
> wrote:
> 
> > http://www.snap.uaf.edu/data.php#dataset=historical_derived_temperature_2km
> > 
> > ^ I don't think that one should be there.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ua-snap/snap-www/issues/117>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/117#issuecomment-10913909.

## 

*
*
*Bruce Crevensten, Web Programmer
*
Scenarios Network for Alaska & Arctic Planning
3352 College Road, 2nd Floor Denali Building
Fairbanks, AK 99709
Phone: 907-474-7134
Fax: 907-474-7151
www.snap.uaf.edu
becrevensten@alaska.edu
