### ISSUE TITLE
Add previous 2 decades to Charts Tool

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#124]
Per a note from an NCAR staff (Shannon McNeeley) posted on Facebook: "This leaves out the most important last two decades. I would like to see this with those included for comparison"

**Comment by takurkowski** [comment]
Let's not.  It will just make the tool more confusing.  It's good as it is
for it's designed purpose.

On Wed, Dec 26, 2012 at 2:13 PM, Bruce Crevensten
notifications@github.comwrote:

> Per a note from an NCAR staff (Shannon McNeeley) posted on Facebook: "This
> leaves out the most important last two decades. I would like to see this
> with those included for comparison"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/124.

## 

_Tom Kurkowski | Operations Lead_
tom.kurkowski@alaska.edu | 907.474.5539
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska | 3352 College Rd | Fairbanks AK 99709
Facebookhttp://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall
  Twitter http://twitter.com/#!/SNAPandACCAP
Flickrhttp://www.flickr.com/photos/snapandaccap/
