### ISSUE TITLE
Add project to web site / K. Cunningham

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#128]
Assessment and Mapping of the Riverine Hydrokinetic Resource in the Continental United States

Bruce/Tom have in email

**Comment by takurkowski** [comment]
Title:
Assessment and Mapping of the Riverine Hydrokinetic Resource in the Continental United States

Description:
This report describes the methodology and results of the most rigorous assessment to date of the riverine hydrokinetic energy resource in the contiguous 48 states and Alaska, excluding tidal waters. The assessment provides estimates of the gross, naturally available resource, termed the theoretical resource, as well as estimates, termed the technically recoverable resource, that account for selected technological factors affecting capture and conversion of the theoretical resource. The technically recoverable resource does not account for all technical constraints on energy capture and conversion.

Project Pic:
![48rivers](https://f.cloud.github.com/assets/1444284/772090/b761cf04-e8fa-11e2-9c5b-cdf384c6f5ea.png)

Contact:
Keith Cunningham
kwcunningham@alaska.edu

Collaborators:
National Renewable Energy Laboratory
'/Volumes/Shared/Outreach/Logos 2/9_Other Logos/National Renewable Energy Laboratory/logo_nrel.jpg'

UAF

UAA
'/Volumes/Shared/Outreach/Logos 2/6_UAA/UAA_3Line_2color_solid.jpg'

Electric Power Research Institute
'/Volumes/Shared/Outreach/Logos 2/9_Other Logos/Electric Power Research Institute/EPRI-logo_RGB_6-x-600.jpg'

link to pdf of report
