### ISSUE TITLE
Ensure we have download metrics for data sets

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#129]
This ticket used to be about "log format string for apache is lacking" but, adding awstats / similar tool forces that issue.

**Comment by brucecrevensten** [comment]
I think for analytics, we've got enough information, so perhaps this is more of a systems-logging level question.

Bob, what do you think?  IIRC the log format on phobos was either nonstandard enough, or somehow problematic such that I made a note to revisit it.

**Comment by brucecrevensten** [comment]
Updated per notes from Tom, we want the ability to track downloads of data products.

**Comment by BobTorgerson** [comment]
As suggested by Bruce, I looked into AWStats as an option for providing log analysis for our Apache services. I currently have AWStats running on phobos.snap.uaf.edu, nyx.snap.uaf.edu, and luna.snap.uaf.edu which provides us with statistics for: http://www.snap.uaf.edu, http://csc.alaska.edu and http://accap.uaf.edu.

Each of these AWStats instances can be visited by appending /awstats/awstats.pl to the end of the respective website domain name such as: http://www.snap.uaf.edu/awstats/awstats.pl

Downloads are one of the options to view from the GUI in AWStats, and I can see examples of the gzipped tar files containing data being listed as having been downloaded. It looks like this software should provide the desired information that we wanted.

**Comment by brucecrevensten** [comment]
migrated to new site repo, closing
