### ISSUE TITLE
Add links to relevant source code for IEM project

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#131]
If the github code is available under the SNAP repository, it'd be nice to provide those links as well.  If we're gonna be open, we gotta do this.  < tom

**Comment by takurkowski** [comment]
IEM model code should be located here for now:
http://www.snap.uaf.edu/project_page.php?projectid=15

Not sure if it's ready.  Alec?

**Comment by takurkowski** [comment]
no action needed for now.

**Comment by brucecrevensten** [comment]
migrated issue to new repo
