### ISSUE TITLE
Update project_page.php to allow correctly-rendered HTML from DB

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#133]
https://github.com/ua-snap/snap-www/blob/test/project_page.php

Generally speaking, we dont' want to put HTML in the DB.  For a low-friction fix to get richer descriptions for projects, we want to get some HTML into the project descriptions fields that displays correctly.  Currently, the project_page.php code injects newlines everywhere -- not what we want when we've got plain html.

This ticket is done when:
- Existing projects continue to display the same way they currently do, without changing things in the DB
- HTML including lists, headers, and image references display correctly, i.e. without added <br/> tags

**Comment by bamelegari** [comment]
there's a commit for this - didn't write the note properly: https://github.com/ua-snap/snap-www/commit/4b3755d14522800ed4670ea7be743614229982af

**Comment by brucecrevensten** [comment]
this is already merged into master branch.
