### ISSUE TITLE
'Exporting Chart' window stays after download begins

### ISSUE THREAD

**Issue by bamelegari** [ua-snap/snap-www#139]
When exporting a high-res png, The secondary "exporting" window that pops up to inform the user that it may take a while to generate their chart stays up after the chart is exported and begins to download, which gives the impression that something is still happening on the server's end regarding that download even though that is not true

**Comment by bamelegari** [comment]
I plan to try and fix this when I implement the license modal click-through, as that is when I noticed it and it may be causing implementation issues.

**Comment by takurkowski** [comment]
yeah, this was a known behavior, but will be good to improve if possible

**Comment by bamelegari** [comment]
its starting to appear, after examining the asynchronosity of and lack of a callback in highcharts, that the only real way to change this behavior is to use some form of highcharts' built-in progress monitoring code, instead of a jquery ui dialog. Otherwise I'm having trouble seeing a way for our javascript to know when the image is done generating and being sent for download.

**Comment by brucecrevensten** [comment]
http://stackoverflow.com/questions/1106377/detect-when-browser-receives-file-download

may get us going in the right direction, but it's a bit on the tricky side.
 Worth checking with Tom about time investment.

On Fri, Jun 14, 2013 at 1:47 PM, bamelegari notifications@github.comwrote:

> its starting to appear, after examining the asynchronosity of and lack of
> a callback in highcharts, that the only real way to change this behavior is
> to use some form of highcharts' built-in progress monitoring code, instead
> of a jquery ui dialog. Otherwise I'm having trouble seeing a way for our
> javascript to know when the image is done generating and being sent for
> download.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/139#issuecomment-19483515
> .

## 

*Bruce Crevensten, Programmer
*
(ACUASI) Alaska Center for UAS Integration
(SNAP) Scenarios Network for Alaska & Arctic Planning
www.snap.uaf.edu

**Comment by bamelegari** [comment]
yea I had seen that one as I looked around -- wasn't sure if we wanted to fiddle with more cookies and what not.

**Comment by brucecrevensten** [comment]
Migrated issue to new site.
