### ISSUE TITLE
IEM content update

### ISSUE THREAD

**Issue by bamelegari** [ua-snap/snap-www#141]
1) Replace image on the IEM project page
2) link from SNAP IEM page to Alaska CSC IEM page
3) link from SNAP IEM page to appropriate data on the SNAP data page
4) update Amy Breen's SNAP 'people' page.

**Comment by bamelegari** [comment]
everything on this issue is now done (via database updates) except for a code change that will help improve the link from the IEM page to the data page, and potential future links to the data page (it consists of adding ids to divs to be used as anchors for links).

**Comment by brucecrevensten** [comment]
Branch merged to add IDs to local data section.

I can't tell if the DB changes are present on the dev site; I'm guessing not, since there's no reference to specific data page IDs.  This work will need to be redone.
