### ISSUE TITLE
Add project and news highlight for Arctic Management Report

### ISSUE THREAD

**Issue by bamelegari** [ua-snap/snap-www#144]
1) add project page (database)
2) add news highlight to front page (code)
3) add three new collaborators to the collaborators section (database)
    -also note these collaborators in the project

**Comment by takurkowski** [comment]
Audubon Alaska
'/Volumes/Shared/Outreach/Logos 2/9_Other Logos/Audubon Alaska/Aud_AK_logo_square.gif'

**Comment by brucecrevensten** [comment]
Project info is present on dev server:

http://pan.snap.uaf.edu/project_page.php?projectid=26

**Comment by brucecrevensten** [comment]
Merged branch associated with this.  Looks like dev server also has the Audubon image, so it can be searched/pulled from there.
