### ISSUE TITLE
new "modelling" landing page

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#147]
Please verify with Tom that mockups and text is ready before working on.  This page will need to be reviewed by other groups before going live as well.

docs should be shared with Bruce and Bryce

Thanks,
Tom

mockups
https://drive.google.com/a/alaska.edu/?tab=mo#folders/0B80FPRFjcI2VbEJVb21ZZk5DcWc

text
https://docs.google.com/a/alaska.edu/document/d/1B35GaBYMWXT37O1Q5GhzzImTenlgdgSeBTWZvqMvWN8/edit

**Comment by bamelegari** [comment]
closing this issue, as the next step has been hit and mockups have been updated (see issue #167)
