### ISSUE TITLE
add below collaborators to collaborators page

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#149]
National Renewable Energy Laboratory
'/Volumes/Shared/Outreach/Logos 2/9_Other Logos/National Renewable Energy Laboratory/logo_nrel.jpg'

UAA
'/Volumes/Shared/Outreach/Logos 2/6_UAA/UAA_3Line_2color_solid.jpg'

Electric Power Research Institute
'/Volumes/Shared/Outreach/Logos 2/9_Other Logos/Electric Power Research Institute/EPRI-logo_RGB_6-x-600.jpg'

**Comment by takurkowski** [comment]
ask Tom about simplification of SNAP Collab page before proceeding with this issue

**Comment by takurkowski** [comment]
and:

Audubon Alaska
'/Volumes/Shared/Outreach/Logos 2/9_Other Logos/Audubon Alaska/Aud_AK_logo_square.gif'

**Comment by bamelegari** [comment]
added all of these -- closed as I move onto the larger scale collaborators page changes
