### ISSUE TITLE
Rectify differences between test database and production database

### ISSUE THREAD

**Issue by bamelegari** [ua-snap/snap-www#150]
It seems that the production database is far more up to date, but we may need to check to ensure that there's no changes hanging out in the test DB that never got re-done for production. Also, we need to decide whether we want to modify the production DB directly or not, at least for the immediate future finishing 1.2.6

**Comment by brucecrevensten** [comment]
Specific changes to check:

-- DB structure on production vs. test (primary keys, mainly)
-- Content/structure changes to individual tables
-- Clearly missing content, etc between version

Bit of a PITA but easy enough to figure.  I'll help.

**Comment by bamelegari** [comment]
the production database was further ahead in all ways, there were no changes hiding in the test database that didn't exist elsewhere. Overwrote test DB with production, case closed.
