### ISSUE TITLE
Link Sarah's bio page to ACCAP web site

### ISSUE THREAD

**Issue by bamelegari** [ua-snap/snap-www#152]
(Previously: update Sarah's bio on the SNAP site).

Expected: clicking on Sarah links to her profile on the ACCAP site.
Loose ends: deal with old links/archived references to her People page.

**Comment by takurkowski** [comment]
## no, don't do the above, simply change the text on her SNAP bio page to the below:

delete her contact info: email, phone, fax

Sarah Trainor is the stakeholder liaison for SNAP, as well Associate Research Professor at the International Arctic Research Center (link), Director of the Alaska Center for Climate Assessment and Policy (link) and the Alaska Fire Science Consortium (link).

To learn more about Sarah, please see her profile on the ACCAP website (link to her ACCAP profile).
