### ISSUE TITLE
SNAP Collaborators page changes #2

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#153]
Delete the long list of collaborators under the "logo cloud".  These are the ones where we tracked their contact info, city, and description.

Then, add links to each organization's homepage from the logos in the logo cloud that remains.

The point here is to reduce the amount of maintenance on this page when we add a new collaborator.  With this approach, we'll simply need to add  new logo and link to their homepage.  We'll let the other orgs maintain their info instead of us providing it.

**Comment by bamelegari** [comment]
This issue should probably remain open: The columns for the information that is now not used due to this change should be dropped from the database, but we obviously can't do that until the change removing the need for them goes live.
