### ISSUE TITLE
Contact person under project: email address links back to same page (wat)

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#156]
http://www.snap.uaf.edu/project_page.php?projectid=13

STR: click on Alison's email address.
Expected: either not linked, or (I don't like this) use a mailto: address.
Actual: takes you back to same page.

**Comment by bamelegari** [comment]
This is actually the case for all email addresses in the contact information sections of projects.

**Comment by bamelegari** [comment]
I put the mailto in because that's the more complicated (barely) of the two changes, but I'm open to whatever you think is better, so I'll leave this issue open until we talk about it.
