### ISSUE TITLE
remodel modeling page

### ISSUE THREAD

**Issue by bamelegari** [ua-snap/snap-www#167]
mockups here:
https://drive.google.com/a/alaska.edu/folderview?id=0B80FPRFjcI2VRUlwVUxFN25QWFU&usp=sharing

**Comment by takurkowski** [comment]
Let's do this...

text for copying and pasting ease located here:
https://docs.google.com/a/alaska.edu/document/d/1B35GaBYMWXT37O1Q5GhzzImTenlgdgSeBTWZvqMvWN8/edit#

**Comment by brucecrevensten** [comment]
Tom's sorting this out on new web site + has a ticket for it there.
