### ISSUE TITLE
add 5 model average for projected snow day data

### ISSUE THREAD

**Issue by bamelegari** [ua-snap/snap-www#176]
Z:\Base_Data\Climate\AK_800m\snow_day_fraction\fs_decadal_mean_monthly_mean_pct_5modelavg_2010_2099.zip

**Comment by brucecrevensten** [comment]
Is this still pending?  It looks like it may be (individual models are available, but not an average), just checking.

**Comment by takurkowski** [comment]
yes, still pending

**Comment by brucecrevensten** [comment]
Closing dupe already copied to new site.
