### ISSUE TITLE
revisit organizational stragety on tools pages

### ISSUE THREAD

**Issue by bamelegari** [ua-snap/snap-www#181]
Both the tools and data page and apps landing page menus are not very extensible (unless the tools page grows by 2 options every time, which I doubt). It's worth either working out some more complex, case by case way to organize the menu buttons or totally remodelling both pages.

**Comment by carolynrosner** [comment]
I can have a look a this and come up with some ideas.

Carolyn

On Thu, Nov 21, 2013 at 10:01 AM, bamelegari notifications@github.comwrote:

> Both the tools and data page and apps landing page menus are not very
> extensible (unless the tools page grows by 2 options every time, which I
> doubt). It's worth either working out some more complex, case by case way
> to organize the menu buttons or totally remodelling both pages.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/181
> .

## 

Carolyn

## 

_Carolyn Rosner_
Science Communicator
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska Fairbanks
Fairbanks AK 99701
775-343-6481

**Comment by bamelegari** [comment]
New ideas are ok with me. Something close to what we have now could still work as well, I'd just have to gut it and redo it in a way that can handle growth.

**Comment by brucecrevensten** [comment]
Closing, vertical layout works for the near term.
