### ISSUE TITLE
Contact us link in the terms of use section (on terms page and data page) does not take you to the contact us form

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#183]
http://www.snap.uaf.edu/terms.php

**Comment by carolynrosner** [comment]
Huh. Weird. The link just goes to the top of the contact page. Anchor link
to lower-down on the page is missing.

2013/11/26 Tom Kurkowski notifications@github.com

> http://www.snap.uaf.edu/terms.php
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/183
> .

## 

Carolyn

## 

_Carolyn Rosner_
Science Communicator
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska Fairbanks
Fairbanks AK 99701
775-343-6481
