### ISSUE TITLE
add same CC license statement to bottom of tools and data page, above header http://pan.snap.uaf.edu/datamaps.php

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#185]

**Comment by brucecrevensten** [comment]
Slightly unsure about placement -- is this what you mean?

![screen shot 2013-12-19 at 10 31 43 am](https://f.cloud.github.com/assets/525049/1785432/39ed9764-68e4-11e3-9800-eb6587787282.png)

**Comment by takurkowski** [comment]
sorry, I meant "bottom of page, above footer".
