### ISSUE TITLE
replace tools and data page sub nav links with simple text of "Explore trends and patterns from past and future climate"

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#186]

**Comment by brucecrevensten** [comment]
I'm unsure what exact text to swap out, here, is this related at all to #187 ?

Or, change all the link text to be identical?  That doesn't seem like what's wanted here.

?

**Comment by takurkowski** [comment]
unrelated to #187 

adding the additional tools means there will not be room on the sub nav bar to include all tools as links there, so I propose not having a sub nav menu and replacing the links there with a simple tag line of "Explore trends and patterns from past and future climate", similar to the Projects and Resources pages.

**Comment by brucecrevensten** [comment]
Oh!  I'd updated that subnav, and the sub-items unexpectedly did fit OK, does this look all right?

![screen shot 2013-12-20 at 6 58 14 am](https://f.cloud.github.com/assets/525049/1791549/a625cf22-698f-11e3-9cb2-3153de2dffc4.png)

**Comment by takurkowski** [comment]
yup, great, good change.
