### ISSUE TITLE
delete the below from the tools and data page and add the second paragraph

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#187]
delete:
All SNAP data, methods, models, and project results are freely available to the public. We do our best to provide data in formats that are accessible to a wide range of users. Currently, all of our data are available for download as GeoTIFF files. Selected maps and data are available for online browsing and download via our web-based Map Tool and our Community Charts page.

Add:
At SNAP, we develop tools that enable you to reveal trends and patterns in climate that are of interest to a wide range of people and organizations.  Please explore the tools below, or download raw data for your own analyses, and please let us know any feedback by contacting us ("contacting us" as link to contact form).

**Comment by BobTorgerson** [comment]
This has been done for the local copy on Pan.
