### ISSUE TITLE
add sea ice icon to tools and data page, icon and mockup attached.

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#189]
![tools and data mockup](https://f.cloud.github.com/assets/1444284/1746297/9a1a6d94-643c-11e3-9be0-5823c2ee7cdb.png)
![hsia_icon](https://f.cloud.github.com/assets/1444284/1746300/9d59df8a-643c-11e3-8f8b-c01ef7d94919.png)

**Comment by takurkowski** [comment]
the arrangement of the icons on the page may need to be re-tweaked, as there are a lot now.

**Comment by brucecrevensten** [comment]
Here's an implementation using the horizontal layout, a touch cramped, perhaps.

![screen shot 2013-12-19 at 11 14 10 am](https://f.cloud.github.com/assets/525049/1785787/30dfa210-68ea-11e3-9321-449e84f260f1.png)

**Comment by takurkowski** [comment]
I think that's ok.  Better might be 3 on top, 2 centered below.

**Comment by brucecrevensten** [comment]
And here's a vertical layout for comparison:
![screen shot 2013-12-19 at 11 34 46 am](https://f.cloud.github.com/assets/525049/1785991/26aeff54-68ed-11e3-996f-568353cc0992.png)

**Comment by takurkowski** [comment]
that works.  Please put in this order from top to bottom:

Comm Charts
Map Tool
Analysis tools
sea ice atlas
Download data

Thanks

**Comment by carolynrosner** [comment]
Nice solution, BC - Vertical arrangement works, and is scalable. Thumbs up!

**Comment by brucecrevensten** [comment]
Final sanity-check, I updated and reordered the submenu items to match the content and new layout:

![screen shot 2013-12-19 at 12 01 11 pm](https://f.cloud.github.com/assets/525049/1786193/bda19356-68f0-11e3-936a-5fae22e3412b.png)
