### ISSUE TITLE
add FAQ for RCPs

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#190]

**Comment by carolynrosner** [comment]
RCP = real climate projections? Happy to help with this, but need more information please!

**Comment by takurkowski** [comment]
ha.  no.

representative concentration pathways.  This is a change from the SRES or scenario approach used in the last round of the IPCC reports.

Some items to cover, that may be one of more FAQs, but relate to eachother:
IPCC AR4 vs IPCC AR5 (AR = assessment report)
CMIP3 vs CMIP5 (hint, they skipped #4 to align the AR #s with the CMIP #s
SRES approach (AR4/CMIP3) vs RCP approach (AR5/CMIP5)

There are lots of great sites that already explain this is detail, so I'd go for a concise summary and then link to reputable sources, IPCC or similar.

https://www.google.com/search?q=rcp+vs+sres&oq=rcp+vs+sres&aqs=chrome..69i57.5503j0j7&sourceid=chrome&espv=210&es_sm=91&ie=UTF-8

**Comment by brucecrevensten** [comment]
Copied to new site issue tracker.
