### ISSUE TITLE
confirm and make sure all "contact us" direct links autoscroll to the form itself.

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#192]

**Comment by brucecrevensten** [comment]
OK, after some investigation, this is because something unusual is going on on this page itself -- either JS is interfering, or the DOM mangle has caught up with us here.  #194 opened to address that.

**Comment by brucecrevensten** [comment]
Derp.  It was just because the selector was targeting an unexpected element on the page.
