### ISSUE TITLE
All sea ice and quantile mapped zip download links fail. please fix by end of Tues

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#204]
these are all the new datasets just added.  They are the top 5 data entries on the data page.  Please inspect and reach out to Bruce if needed.

**Comment by brucecrevensten** [comment]
The relevant data files simply aren't present in the online directory.
 Here's the list of filenames that are expected:

http://www.snap.uaf.edu/files/data/monthly/sic_con_pct_5-Models_historical_01-12_1860-2005.zip
http://www.snap.uaf.edu/files/data/monthly/sic_con_pct_5-Models_rcp85_01-12_2006-2100.zip
http://www.snap.uaf.edu/files/data/monthly/tas_mean_C_AR5_3-Models_historical_365_1958-2005.zip
http://www.snap.uaf.edu/files/data/monthly/tas_mean_C_AR5_3-Models_rcp60_365_2006-2100.zip
http://www.snap.uaf.edu/files/data/monthly/tas_mean_C_AR5_3-Models_rcp85_365_2006-2100.zip
http://www.snap.uaf.edu/files/data/monthly/uas_mean_mps_AR5_3-Models_historical_365_1958-2005.zip
http://www.snap.uaf.edu/files/data/monthly/vas_mean_mps_AR5_3-Models_historical_365_1958-2005.zip
http://www.snap.uaf.edu/files/data/monthly/uas_mean_mps_AR5_3-Models_rcp60_365_2006-2100.zip
http://www.snap.uaf.edu/files/data/monthly/uas_mean_mps_AR5_3-Models_rcp85_365_2006-2100.zip
http://www.snap.uaf.edu/files/data/monthly/vas_mean_mps_AR5_3-Models_rcp60_365_2006-2100.zip
http://www.snap.uaf.edu/files/data/monthly/vas_mean_mps_AR5_3-Models_rcp85_365_2006-2100.zip

From inspection, I am unsure if all file names are correct -- are the
uas/vas ones correct?  Either way, just moving the relevant files to the
correct location will work (and I can update the link names if required).

On Mon, Jan 6, 2014 at 10:30 AM, Tom Kurkowski notifications@github.comwrote:

> these are all the new datasets just added. They are the top 5 data entries
> on the data page. Please inspect and reach out to Bruce if needed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/204
> .

## 

_Bruce Crevensten_

_Senior Software Engineer_
(SNAP) Scenarios Network for Alaska & Arctic Planning
www.snap.uaf.edu

**Comment by takurkowski** [comment]
see email for location of zips 

root directory for zip files:
Z:\web_data_zips\AR5\

**Comment by BobTorgerson** [comment]
I have moved these files into their expected location for the web service to be able to access them. I have confirmed that I am able to download these files now from the data web page.

**Comment by brucecrevensten** [comment]
Re-confirmed via automated link checker.  I think this issue is resolved.

On Mon, Jan 6, 2014 at 12:37 PM, BobTorgerson notifications@github.comwrote:

> I have moved these files into their expected location for the web service
> to be able to access them. I have confirmed that I am able to download
> these files now from the data web page.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/204#issuecomment-31689777
> .

## 

_Bruce Crevensten_

_Senior Software Engineer_
(SNAP) Scenarios Network for Alaska & Arctic Planning
www.snap.uaf.edu

**Comment by takurkowski** [comment]
sweet, thanks to you both!

Tom

On Mon, Jan 6, 2014 at 12:41 PM, Bruce Crevensten
notifications@github.comwrote:

> Re-confirmed via automated link checker. I think this issue is resolved.
> 
> On Mon, Jan 6, 2014 at 12:37 PM, BobTorgerson notifications@github.comwrote:
> 
> > I have moved these files into their expected location for the web
> > service
> > to be able to access them. I have confirmed that I am able to download
> > these files now from the data web page.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ua-snap/snap-www/issues/204#issuecomment-31689777>
> > .
> 
> ## 
> 
> _Bruce Crevensten_
> 
> _Senior Software Engineer_
> (SNAP) Scenarios Network for Alaska & Arctic Planning
> www.snap.uaf.edu
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/204#issuecomment-31690176
> .

## 

_Tom Kurkowski | Operations Lead_
tom.kurkowski@alaska.edu | 907.474.5539
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska | 3352 College Rd | Fairbanks AK 99709
Facebookhttp://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall
  Twitter http://twitter.com/#!/SNAPandACCAP
