### ISSUE TITLE
Archive JB's work?

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#205]

**Comment by takurkowski** [comment]
what's the content?  I'll email him.

Tom

On Wed, Jan 15, 2014 at 11:26 AM, Bruce Crevensten <notifications@github.com

> wrote:
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/205
> .

## 

_Tom Kurkowski | Operations Lead_
tom.kurkowski@alaska.edu | 907.474.5539
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska | 3352 College Rd | Fairbanks AK 99709
Facebookhttp://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall
  Twitter http://twitter.com/#!/SNAPandACCAP

**Comment by brucecrevensten** [comment]
http://www.snap.uaf.edu/jbailey/

and

http://www.snap.uaf.edu/earth/

...I think that covers it.  This content is actively accessed, from what I
can check from logs.

On Wed, Jan 15, 2014 at 3:07 PM, Tom Kurkowski notifications@github.comwrote:

> what's the content? I'll email him.
> 
> Tom
> 
> On Wed, Jan 15, 2014 at 11:26 AM, Bruce Crevensten <
> notifications@github.com
> 
> > wrote:
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ua-snap/snap-www/issues/205>
> > .
> 
> ## 
> 
> _Tom Kurkowski | Operations Lead_
> tom.kurkowski@alaska.edu | 907.474.5539
> Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
> University of Alaska | 3352 College Rd | Fairbanks AK 99709
> Facebook<
> http://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall>
> Twitter http://twitter.com/#!/SNAPandACCAP
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/205#issuecomment-32429824
> .

## 

_Bruce Crevensten_

_Senior Software Engineer_
(SNAP) Scenarios Network for Alaska & Arctic Planning
www.snap.uaf.edu
