### ISSUE TITLE
Add sea ice atlas downloads to data page

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#206]

**Comment by brucecrevensten** [comment]
For the extent, do we want to just use the image of Alaska we've currently got, noting in the text that it's sea ice from 75N etc as a bounding box?  Or, create a new image showing the actual bounding box?

**Comment by carolynrosner** [comment]
Do you mean the SNAP Tools and Data Page? Right now that's an
ice-concentration illustration ...

Generally speaking, it'd be good to have a new image showing the actual
bounding box AND a little text explaining the geographic extent (sea ice
from 75N etc) a little more. Guess it depends on how big this image is ...
and where it is ... I could help with image creation if needed.

On Mon, Feb 3, 2014 at 5:01 PM, Bruce Crevensten
notifications@github.comwrote:

> For the extent, do we want to just use the image of Alaska we've currently
> got, noting in the text that it's sea ice from 75N etc as a bounding box?
> Or, create a new image showing the actual bounding box?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/206#issuecomment-34020147
> .

## 

Carolyn

## 

_Carolyn Rosner_
Science Communicator
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska Fairbanks
Fairbanks AK 99701
775-343-6481

**Comment by takurkowski** [comment]
we'll create a small map thumbnail showing the extent of the data, likely
highlighting the water area but including the land for visual reference.

All of our other data is served as geotiffs.  Can we get the "final" sea
ice data as geotiffs?  I suspect Michael can convert the ncdf or database
dump when available.

Once I finish the metadata for this data, we'll use a small simple snippet
of that for a short explanation on the data page.  "Sea ice data is cool,
we have it for monthly and weekly timesteps..etc", just like all the other
datasets.

Tom

On Mon, Feb 3, 2014 at 4:01 PM, Bruce Crevensten
notifications@github.comwrote:

> For the extent, do we want to just use the image of Alaska we've currently
> got, noting in the text that it's sea ice from 75N etc as a bounding box?
> Or, create a new image showing the actual bounding box?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/206#issuecomment-34020147
> .

## 

_Tom Kurkowski | Operations Lead_
tom.kurkowski@alaska.edu | 907.474.5539
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska | 3352 College Rd | Fairbanks AK 99709
Facebookhttp://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall
  Twitter http://twitter.com/#!/SNAPandACCAP

**Comment by brucecrevensten** [comment]
Michael [@earthscientist] and I are going to generate the extent preview
tomorrow.

Can we have a benefit/consequence discussion around NetCDF v. GeoTIFF?
 Digging into tools like Panoply gave me a new perspective on
time-series-aware tooling.  We've already got the data set up as GeoTIFF to
drive Mapserver, so no sweat either / both ways.

On Tue, Feb 4, 2014 at 3:33 PM, Tom Kurkowski notifications@github.comwrote:

> we'll create a small map thumbnail showing the extent of the data, likely
> highlighting the water area but including the land for visual reference.
> 
> All of our other data is served as geotiffs. Can we get the "final" sea
> ice data as geotiffs? I suspect Michael can convert the ncdf or database
> dump when available.
> 
> Once I finish the metadata for this data, we'll use a small simple snippet
> of that for a short explanation on the data page. "Sea ice data is cool,
> we have it for monthly and weekly timesteps..etc", just like all the other
> datasets.
> 
> Tom
> 
> On Mon, Feb 3, 2014 at 4:01 PM, Bruce Crevensten
> notifications@github.comwrote:
> 
> > For the extent, do we want to just use the image of Alaska we've
> > currently
> > got, noting in the text that it's sea ice from 75N etc as a bounding box?
> > Or, create a new image showing the actual bounding box?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ua-snap/snap-www/issues/206#issuecomment-34020147>
> > .
> 
> ## 
> 
> _Tom Kurkowski | Operations Lead_
> tom.kurkowski@alaska.edu | 907.474.5539
> 
> Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
> University of Alaska | 3352 College Rd | Fairbanks AK 99709
> Facebook<
> http://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall>
> Twitter http://twitter.com/#!/SNAPandACCAP
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/206#issuecomment-34125457
> .

## 

_Bruce Crevensten_

_Senior Software Engineer_
(SNAP) Scenarios Network for Alaska & Arctic Planning
www.snap.uaf.edu

**Comment by takurkowski** [comment]
Re: NetCDF v. GeoTIFF?

Sure, it comes up almost monthly.  Which version of NetCDF?  ha.

On Tue, Feb 4, 2014 at 3:43 PM, Bruce Crevensten
notifications@github.comwrote:

> Michael [@earthscientist] and I are going to generate the extent preview
> tomorrow.
> 
> Can we have a benefit/consequence discussion around NetCDF v. GeoTIFF?
> Digging into tools like Panoply gave me a new perspective on
> time-series-aware tooling. We've already got the data set up as GeoTIFF to
> drive Mapserver, so no sweat either / both ways.
> 
> On Tue, Feb 4, 2014 at 3:33 PM, Tom Kurkowski <notifications@github.com
> 
> > wrote:
> > 
> > we'll create a small map thumbnail showing the extent of the data, likely
> > highlighting the water area but including the land for visual reference.
> > 
> > All of our other data is served as geotiffs. Can we get the "final" sea
> > ice data as geotiffs? I suspect Michael can convert the ncdf or database
> > dump when available.
> > 
> > Once I finish the metadata for this data, we'll use a small simple
> > snippet
> > of that for a short explanation on the data page. "Sea ice data is cool,
> > we have it for monthly and weekly timesteps..etc", just like all the
> > other
> > datasets.
> > 
> > Tom
> > 
> > On Mon, Feb 3, 2014 at 4:01 PM, Bruce Crevensten
> > notifications@github.comwrote:
> > 
> > > For the extent, do we want to just use the image of Alaska we've
> > > currently
> > > got, noting in the text that it's sea ice from 75N etc as a bounding
> > > box?
> > > Or, create a new image showing the actual bounding box?
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/ua-snap/snap-www/issues/206#issuecomment-34020147>
> > > .
> > 
> > ## 
> > 
> > _Tom Kurkowski | Operations Lead_
> > tom.kurkowski@alaska.edu | 907.474.5539
> > 
> > Scenarios Network for Alaska & Arctic Planning <http://www.snap.uaf.edu/
> > 
> > University of Alaska | 3352 College Rd | Fairbanks AK 99709
> > Facebook<
> > http://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall>
> > Twitter http://twitter.com/#!/SNAPandACCAP
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ua-snap/snap-www/issues/206#issuecomment-34125457>
> > .
> 
> ## 
> 
> _Bruce Crevensten_
> 
> _Senior Software Engineer_
> (SNAP) Scenarios Network for Alaska & Arctic Planning
> www.snap.uaf.edu
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/206#issuecomment-34126177
> .

## 

_Tom Kurkowski | Operations Lead_
tom.kurkowski@alaska.edu | 907.474.5539
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska | 3352 College Rd | Fairbanks AK 99709
Facebookhttp://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall
  Twitter http://twitter.com/#!/SNAPandACCAP
