### ISSUE TITLE
Upload Snow fraction script to github and link to github URL from 2 relevant locations on SNAP data page.

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#211]
files located here:
http://www.snap.uaf.edu/webshared/takurkowski/snowfraction_code.zip

**Comment by carolynrosner** [comment]
I would like to add this info to the data page on the new site, but not
sure how to go about it. Any assistance would be appreciated!

On Mon, May 5, 2014 at 1:19 PM, Tom Kurkowski notifications@github.comwrote:

> files located here:
> http://www.snap.uaf.edu/webshared/takurkowski/snowfraction_code.zip
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/211
> .

## 

Carolyn

## 

_Carolyn Rosner_
Science Communicator
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska Fairbanks
Fairbanks AK 99701
775-343-6481

**Comment by carolynrosner** [comment]
If someone can Upload Snow fraction script to github, I can then get that
link, and add to the data_downloads.php file for the new site. Just so link
is current when new site is live.

On Mon, May 5, 2014 at 2:57 PM, Carolyn Rosner crosner@alaska.edu wrote:

> I would like to add this info to the data page on the new site, but not
> sure how to go about it. Any assistance would be appreciated!
> 
> On Mon, May 5, 2014 at 1:19 PM, Tom Kurkowski notifications@github.comwrote:
> 
> > files located here:
> > http://www.snap.uaf.edu/webshared/takurkowski/snowfraction_code.zip
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/211
> > .
> 
> ## 
> 
> Carolyn
> 
> ## 
> 
> _Carolyn Rosner_
> Science Communicator
> Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
> University of Alaska Fairbanks
> Fairbanks AK 99701
> 775-343-6481

## 

Carolyn

## 

_Carolyn Rosner_
Science Communicator
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska Fairbanks
Fairbanks AK 99701
775-343-6481

**Comment by carolynrosner** [comment]
With Bruce's help, I have pushed the files in the .zip to the snowfraction repo. 

Questions:
--Which one of the files is the script? Do all of them comprise the script?
--There is no existing link to a snow fraction script on the SNAP data page (in the 2 relevant locations). Am I to create one?

**Comment by takurkowski** [comment]
Yes, please, and thanks for jumping on this.

Upload Snow fraction script to github, sounds like you did this

 and link to github URL from 2 relevant locations on SNAP data page

relevant locations being the 2 snow fraction data sets on the data page.

perhaps after: "Detailed information on the construction of this data and
its implications is available in this
paper.http://www.snap.uaf.edu/attachments/McAfee2013_snowDay.pdf
(PDF,
3.27MB)"

"Scripts used to generate this data available at [insert github repo URL]"

I suppose the repo would also have to be a public repo.

Some of those files are scripts, some are Rdata files, and there's also a
readme.  In an ideal world, and perhaps CKAN or Drupal will allow this, we
can have consistent (and maybe required) places for serving the actual data
files, spatial metadata, additional metadata, links to the code used to
produce the data, and links to supporting information. Right now, if this
information is provided, I try and make sure we share as much as possible
somewhere.  Sometimes that is on the data page, sometimes it's in the
metadata.

Thanks
Tom

On Tue, May 6, 2014 at 11:48 AM, Carolyn Rosner notifications@github.comwrote:

> With Bruce's help, I have pushed the files in the .zip to the snowfraction
> repo.
> 
> Questions:
> --Which one of the files is the script? Do all of them comprise the script?
> --There is no existing link to a snow fraction script on the SNAP data
> page (in the 2 relevant locations). Am I to create one?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/211#issuecomment-42349917
> .

## 

_Tom Kurkowski | Operations Lead_
tom.kurkowski@alaska.edu | 907.474.5539
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska | 3352 College Rd | Fairbanks AK 99709
Facebookhttp://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall
  Twitter http://twitter.com/#!/SNAPandACCAP

**Comment by carolynrosner** [comment]
Thanks for that. Repo is public, and link to scripts has been added to the data downloads page on new SNAP. Have not added to existing SNAP site; OK to not update existing SNAP until new SNAP is launched?

**Comment by takurkowski** [comment]
let's get this live on the new site, so we can use the existing site as
truth when we move to CKAN (which may be used instead of the existing new
site data page.

Tom

On Wed, May 7, 2014 at 9:01 AM, Carolyn Rosner notifications@github.com
wrote:

> Thanks for that. Clears things up. Repo is public, and link to scripts has
> been added to the data downloads page on new SNAP. Have not added to
> existing SNAP site; OK to not update existing SNAP until new SNAP is
> launched?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ua-snap/snap-www/issues/211#issuecomment-42453953.

## 

_Tom Kurkowski | Operations Lead_
tom.kurkowski@alaska.edu | 907.474.5539
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska | 930 Koyukuk Drive | Fairbanks AK 99775
Facebook
http://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall
Twitter http://twitter.com/#!/SNAPandACCAP

**Comment by carolynrosner** [comment]
Sounds good. It actually _is_ on the new site, but the styling is still a
little goofy. Working on making it look better...

On Fri, Jun 27, 2014 at 3:24 PM, Tom Kurkowski notifications@github.com
wrote:

> let's get this live on the new site, so we can use the existing site as
> truth when we move to CKAN (which may be used instead of the existing new
> site data page.
> 
> Tom
> 
> On Wed, May 7, 2014 at 9:01 AM, Carolyn Rosner notifications@github.com
> wrote:
> 
> > Thanks for that. Clears things up. Repo is public, and link to scripts
> > has
> > been added to the data downloads page on new SNAP. Have not added to
> > existing SNAP site; OK to not update existing SNAP until new SNAP is
> > launched?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ua-snap/snap-www/issues/211#issuecomment-42453953.
> 
> ## 
> 
> _Tom Kurkowski | Operations Lead_
> tom.kurkowski@alaska.edu | 907.474.5539
> Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
> University of Alaska | 930 Koyukuk Drive | Fairbanks AK 99775
> Facebook
> http://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall
> Twitter http://twitter.com/#!/SNAPandACCAP
> 
> —
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ua-snap/snap-www/issues/211#issuecomment-47406750.

## 

Carolyn

## 

_Carolyn Rosner_
Designer + Science Communicator
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska Fairbanks
Fairbanks AK 99701
775-343-6481

**Comment by takurkowski** [comment]
sorry, I meant on the current site, let's get this on the current site.

Tom

On Fri, Jun 27, 2014 at 2:53 PM, Carolyn Rosner notifications@github.com
wrote:

> Sounds good. It actually _is_ on the new site, but the styling is still a
> little goofy. Working on making it look better...
> 
> On Fri, Jun 27, 2014 at 3:24 PM, Tom Kurkowski notifications@github.com
> wrote:
> 
> > let's get this live on the new site, so we can use the existing site as
> > truth when we move to CKAN (which may be used instead of the existing
> > new
> > site data page.
> > 
> > Tom
> > 
> > On Wed, May 7, 2014 at 9:01 AM, Carolyn Rosner notifications@github.com
> > 
> > wrote:
> > 
> > > Thanks for that. Clears things up. Repo is public, and link to scripts
> > > has
> > > been added to the data downloads page on new SNAP. Have not added to
> > > existing SNAP site; OK to not update existing SNAP until new SNAP is
> > > launched?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/ua-snap/snap-www/issues/211#issuecomment-42453953.
> > 
> > ## 
> > 
> > _Tom Kurkowski | Operations Lead_
> > tom.kurkowski@alaska.edu | 907.474.5539
> > Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
> > 
> > University of Alaska | 930 Koyukuk Drive | Fairbanks AK 99775
> > Facebook
> > http://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall
> > Twitter http://twitter.com/#!/SNAPandACCAP
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/ua-snap/snap-www/issues/211#issuecomment-47406750.
> 
> ## 
> 
> Carolyn
> 
> ## 
> 
> _Carolyn Rosner_
> Designer + Science Communicator
> Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
> University of Alaska Fairbanks
> Fairbanks AK 99701
> 775-343-6481
> 
> —
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ua-snap/snap-www/issues/211#issuecomment-47408516.

## 

_Tom Kurkowski | Operations Lead_
tom.kurkowski@alaska.edu | 907.474.5539
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska | 930 Koyukuk Drive | Fairbanks AK 99775
Facebook
http://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall
Twitter http://twitter.com/#!/SNAPandACCAP

**Comment by brucecrevensten** [comment]
Copied to new site, closing.
