### ISSUE TITLE
Remove Katie Kennedy from SNAP People page

### ISSUE THREAD

**Issue by carolynrosner** [ua-snap/snap-www#213]
She's no longer with SNAP and asked to be removed ... and I'm not sure how to do it myself.

**Comment by brucecrevensten** [comment]
I can nail this one soon as part of some updates that are ongoing.

On Mon, Jun 9, 2014 at 2:33 PM, Carolyn Rosner notifications@github.com
wrote:

> She's no longer with SNAP and asked to be removed ... and I'm not sure how
> to do it myself.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ua-snap/snap-www/issues/213.

## 

_Bruce Crevensten_

_Senior Software Engineer_
(SNAP) Scenarios Network for Alaska & Arctic Planning
www.snap.uaf.edu
