### ISSUE TITLE
Updates to people page

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#22]
Per Scott:
1. How about all the research faculty are called simply research faculty. That list should be Sarah, Nancy, John, Todd, and Keith.
2. To be consistent with the other SNAP leaders how about adding Professor to me.
3. Let's call all graduate students simply graduate students. That list should be Nicole, Winslow, and Carson.
4. Let's change Mark to Statistician.
5. We need to add Stephanie McAfee as a Post Doctoral Fellow, get a pic, and a blurb.
6. We need to add Jennifer Northway as the Alaska Fire Science Consortium coordinator, a pic, and a blurb.
7. Jane, Keith, Lena, Matt, Mimi, Dustin, and Tracy still needs a blurb (you probably know this). Let me know if I can help provide
   incentive to submit a blurb.
8. It would be nice to highlight our interns (I'd lump student hires in that group too). I don't think they need a blurb, but a picture would be great. So, we've got the ice atlas guy, Dustin's guy, Piia, and Julien. Am I missing anyone?

**Comment by takurkowski** [comment]
most bios are located here..Y:\SNAP website\People\Bios&Publications

Please update with these and then let me know who is missing and I can send out a final request.

**Comment by takurkowski** [comment]
pic of steph attached here...https://projects.snap.uaf.edu/issues/622

**Comment by brucecrevensten** [comment]
[testing if attachments done in email come through to github in a sane way
-- Tom, tell me if you get an email with an attachment of the GI logo]

On Wed, Feb 29, 2012 at 10:13 AM, takurkowski <
reply@reply.github.com

> wrote:
> 
> pic of steph attached here...https://projects.snap.uaf.edu/issues/622
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ua-snap/snap-www/issues/22#issuecomment-4244548

## 

*
*
*Bruce Crevensten, Web Programmer
*
Scenarios Network for Alaska & Arctic Planning
3352 College Road, 2nd Floor Denali Building
Fairbanks, AK 99709
Phone: 907-474-7134
Fax: 907-474-7151
www.snap.uaf.edu
becrevensten@alaska.edu

**Comment by brucecrevensten** [comment]
item 1 from Scott's list is done.

**Comment by brucecrevensten** [comment]
re 2nd item on list, I added 'Research Faculty' to Scott's title -- let me know if this isn't OK.

**Comment by brucecrevensten** [comment]
number 3 is done.

**Comment by brucecrevensten** [comment]
item 4 is completed.

**Comment by brucecrevensten** [comment]
item 5 is completed.

**Comment by brucecrevensten** [comment]
Jen Northway's added, but still need a bio for her.

**Comment by brucecrevensten** [comment]
Mimi, Keith, Lena's bios are posted; missing them for Jane, Jen, Tracy, Dustin.

**Comment by brucecrevensten** [comment]
I don't have photos/etc for number 8.

**Comment by brucecrevensten** [comment]
I've done as many of these as I can, so I'm bumping this to 1.0.8.

**Comment by brucecrevensten** [comment]
add Tracy's bio:

```
Tracy Rogers is a research assistant with SNAP and the Alaska Climate
Science Center. He recently finished his Master's degree at UAF,
studying Arctic sea ice and climate change. His thesis focused on
regional variations in sea ice extent, global climate model
performance in the Arctic, and future scenarios of Arctic marine
access.
```

**Comment by brucecrevensten** [comment]
Add Jane's new photo/bio (in email).

**Comment by carolynrosner** [comment]
Adding comment to this thread re: new photos (Todd Paris pro head shots) and new layout for People page. I also have pic and bio to add to this page. Once I am up to speed on making edits to the SNAP website, I would volunteer to take on the updating of this page.
