### ISSUE TITLE
upload snow fraction 5modelAvg

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#220]
We didn't have a 5 model average for our projected snow day fraction data, so I created one. At your convenience, can you please upload it to the website? The zip file is here:
Z:\Base_Data\Climate\AK_800m\snow_day_fraction\fs_decadal_mean_monthly_mean_pct_5modelavg_2010_2099.zip

just to confirm, this would simply be a new zip download link (no additional metadata link needed) under:

Projected Decadal Averages Of Monthly Snow-day Fraction 771m CMIP3/AR4

{list of individual models}
5 model average zip link

**Comment by brucecrevensten** [comment]
copied to new site repo
