### ISSUE TITLE
Text fix on Data page

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#23]
---------- Forwarded message ----------
From:  contact-form@phobos.snap.uaf.edu
Date: Sun, Feb 26, 2012 at 6:44 PM
Subject: SNAP Web contact form re: Becoming a SNAP collaborator
To: nlfresco@alaska.edu

From: Brian Houseman
Email provided: brian_houseman@nps.gov

On your data page, the historical monthly temperature and precip
dataset shows that it was derived using PRISM data from 1961-2000.
The actual metadata file for this product says 1961-1990, as does the
PRISM website.

**Comment by brucecrevensten** [comment]
Tom, can you take a look and see what the correct info should be here?  Right now there's these ranges for PRISM baseline:

1971-2000 PRISM
1961-2000 PRISM

Can you verify what we should have on the site?

**Comment by takurkowski** [comment]
2km data uses a baseline reference climate of
1961-1990 PRISM

771 m data uses a baseline reference climate of
1971-2000 PRISM

**Comment by takurkowski** [comment]
1961-2000 PRISM does not exist
