### ISSUE TITLE
make a logos page for downloading logos

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#3]
make a page with our logos and/or a link to the page the company made for us

(this ticket had started by asking about the ticket system, I'm transforming it to illustrated some of the aspects of the ticket system).

**Comment by brucecrevensten** [comment]
Got it -- idea: want a 10 minute overview of how the github issues are like/unlike Redmine? Can-do if you want!

**Comment by takurkowski** [comment]
sure.

Tom
...........O
......(**_|/_**_)
.........../

On Thu, Feb 16, 2012 at 12:09 PM, Bruce Crevensten <
reply@reply.github.com

> wrote:
> 
> Got it -- idea: want a 10 minute overview of how the github issues are
> like/unlike Redmine? Can-do if you want!
>

**Comment by brucecrevensten** [comment]
Closed issue, this was deployed in 1.0.5 -- closing here for book-keeping.
