### ISSUE TITLE
text to fix here...http://www.snap.uaf.edu/people_page.php?id=18

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#31]
"He founded and managed two <success> geospatial..."

please change to "successFUL"

**Comment by brucecrevensten** [comment]
Fixed.

On Fri, Mar 9, 2012 at 6:45 PM, takurkowski <
reply@reply.github.com

> wrote:
> 
> "He founded and managed two <success> geospatial..."
> 
> please change to "successFUL"
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ua-snap/snap-www/issues/31

## 

*
*
*Bruce Crevensten, Web Programmer
*
Scenarios Network for Alaska & Arctic Planning
3352 College Road, 2nd Floor Denali Building
Fairbanks, AK 99709
Phone: 907-474-7134
Fax: 907-474-7151
www.snap.uaf.edu
becrevensten@alaska.edu
