### ISSUE TITLE
change the map tool metadata window 

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#38]
https://projects.snap.uaf.edu/issues/727

**Comment by takurkowski** [comment]
looks good! it was working but now no metadata links are working, this ticket can be closed if it is unrelated to current down...ness.

**Comment by brucecrevensten** [comment]
I don't suspect it's related, but I'll wait until Dustin's confirmed an
all-clear before closing, just in case it is some zany thing I may need to
code around.

On Mon, Mar 26, 2012 at 6:20 PM, Tom Kurkowski <
reply@reply.github.com

> wrote:
> 
> looks good! it was working but now no metadata links are working, this
> ticket can be closed if it is unrelated to current down...ness.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ua-snap/snap-www/issues/38#issuecomment-4708005

## 

*
*
*Bruce Crevensten, Web Programmer
*
Scenarios Network for Alaska & Arctic Planning
3352 College Road, 2nd Floor Denali Building
Fairbanks, AK 99709
Phone: 907-474-7134
Fax: 907-474-7151
www.snap.uaf.edu
becrevensten@alaska.edu

**Comment by takurkowski** [comment]
dustin restarted geonetwork and it's fine now, he also added a flag to his notification software for future occurrences.
