### ISSUE TITLE
add caption to table of models

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#39]
Please add the below text as a small font caption to the table of models on this page...http://www.snap.uaf.edu/downscaling.php

Similar to the caption below the map on the community charts page.

"We acknowledge the World Climate Research Programme's Working Group on Coupled Modeling, which is responsible for CMIP, and we thank all the climate modeling groups for producing and making available their model output. For CMIP the U.S. Department of Energy's Program for Climate Model Diagnosis and Intercomparison provides coordinating support and led development of software infrastructure in partnership with the Global Organization for Earth System Science Portals."

**Comment by brucecrevensten** [comment]
https://projects.snap.uaf.edu/issues/728

**Comment by brucecrevensten** [comment]
Small grammar tweak in the blurb:  changed "led" to "leads" to align tense with "provides," to read:

...[the US Department of Energy's ....] and Intercomparison provides coordinating support and _leads_ development of software infrastructure...

**Comment by takurkowski** [comment]
thanks
