### ISSUE TITLE
reduce size of downscaling graphic 

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#42]
http://www.snap.uaf.edu/downscaling.php

it's too big.

x-ref: https://projects.snap.uaf.edu/issues/729

**Comment by takurkowski** [comment]
that looks good, can you please reduce the size of the PRISM logo to be on a similar scale as the other logo images?  It sticks out a lot now.

Sorry for increasing the scope of this one...I think this one's doable:)

**Comment by brucecrevensten** [comment]
OK, done -- I also floated all those images to the right, after some
reading suggested that the left-margin of the text not be interrupted for
non-major content (it keeps the emphasis on the narrative).  I think it's
easier to read, but ??

I kept the downscaling one on the left, just because that's a core diagram.

On Mon, Mar 26, 2012 at 6:15 PM, Tom Kurkowski <
reply@reply.github.com

> wrote:
> 
> that looks good, can you please reduce the size of the PRISM logo to be on
> a similar scale as the other logo images?  It sticks out a lot now.
> 
> Sorry for increasing the scope of this one...I think this one's doable:)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ua-snap/snap-www/issues/42#issuecomment-4707944

## 

*
*
*Bruce Crevensten, Web Programmer
*
Scenarios Network for Alaska & Arctic Planning
3352 College Road, 2nd Floor Denali Building
Fairbanks, AK 99709
Phone: 907-474-7134
Fax: 907-474-7151
www.snap.uaf.edu
becrevensten@alaska.edu

**Comment by takurkowski** [comment]
looks great.
