### ISSUE TITLE
make link to specific data heading unique to allow direct linking to data page with scroll down and open data heading

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#45]
http://www.snap.uaf.edu/data.php

**Comment by brucecrevensten** [comment]
Hi -- just logging this, or do you want it in 1.0.8?  (Shouldn't be too big
a deal unless I get really short on time.  I know that the underlying libs
for the accordion-headers accommodate this in some form or another.)

2012/3/26 Tom Kurkowski <
reply@reply.github.com

> http://www.snap.uaf.edu/data.php
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ua-snap/snap-www/issues/45

## 

*
*
*Bruce Crevensten, Web Programmer
*
Scenarios Network for Alaska & Arctic Planning
3352 College Road, 2nd Floor Denali Building
Fairbanks, AK 99709
Phone: 907-474-7134
Fax: 907-474-7151
www.snap.uaf.edu
becrevensten@alaska.edu

**Comment by takurkowski** [comment]
I just threw it in there for a future iteration, but feel free to get it in
1.0.8 if you'd like.  I get a lot of questions about where to find a
specific dataset on our site, and this little fix should help folks get
where they need to be.

Tom

On Mon, Mar 26, 2012 at 12:31 PM, Bruce Crevensten <
reply@reply.github.com

> wrote:
> 
> Hi -- just logging this, or do you want it in 1.0.8?  (Shouldn't be too big
> a deal unless I get really short on time.  I know that the underlying libs
> for the accordion-headers accommodate this in some form or another.)
> 
> 2012/3/26 Tom Kurkowski <
> reply@reply.github.com
> 
> > http://www.snap.uaf.edu/data.php
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ua-snap/snap-www/issues/45
> 
> ## 
> 
> *
> *
> *Bruce Crevensten, Web Programmer
> *
> Scenarios Network for Alaska & Arctic Planning
> 3352 College Road, 2nd Floor Denali Building
> Fairbanks, AK 99709
> Phone: 907-474-7134
> Fax: 907-474-7151
> www.snap.uaf.edu
> becrevensten@alaska.edu
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ua-snap/snap-www/issues/45#issuecomment-4703451

## 

_Tom Kurkowski | Operations Lead_
tom.kurkowski@alaska.edu | 907.474.5539
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska | 3352 College Rd | Fairbanks AK 99709
Facebookhttp://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall
  Twitter http://twitter.com/#!/SNAPandACCAP
Flickrhttp://www.flickr.com/photos/snapandaccap/

**Comment by takurkowski** [comment]
looks good
