### ISSUE TITLE
add icons/blurbs to list of links to tools

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#52]
Along the lines of some of the lists of things with icons on this page: http://www.smashingmagazine.com/2009/03/03/how-to-use-icons-to-support-content-in-web-design/

Add list of icons/text blurbs for map tool, charts tool, and data.

**Comment by bamelegari** [comment]
I believe this is complete?: http://www.snap.uaf.edu/datamaps.php
