### ISSUE TITLE
typo or copyo

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#57]
http://www.snap.uaf.edu/people_page.php?id=15

Mimi?s

**Comment by brucecrevensten** [comment]
Pasteo.  It's pretty common for the ' char in Word to turn into a ? because the charset doesn't get transformed right when it's pasted, and while I _do_ scan for this, I miss 'em.  fixed.  thx.

**Comment by takurkowski** [comment]
thanks

On Wed, Apr 18, 2012 at 2:23 PM, Bruce Crevensten <
reply@reply.github.com

> wrote:
> 
> Pasteo.  It's pretty common for the ' char in Word to turn into a ?
> because the charset doesn't get transformed right when it's pasted, and
> while I _do_ scan for this, I miss 'em.  fixed.  thx.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ua-snap/snap-www/issues/57#issuecomment-5210296

## 

_Tom Kurkowski | Operations Lead_
tom.kurkowski@alaska.edu | 907.474.5539
Scenarios Network for Alaska & Arctic Planning http://www.snap.uaf.edu/
University of Alaska | 3352 College Rd | Fairbanks AK 99709
Facebookhttp://www.facebook.com/pages/SNAP-and-ACCAP/112992248723524?v=wall
  Twitter http://twitter.com/#!/SNAPandACCAP
Flickrhttp://www.flickr.com/photos/snapandaccap/
