### ISSUE TITLE
FAQ text changes

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/snap-www#60]
How should I give attribution to SNAP?

When the publication medium allows it, please include the SNAP logo and a link back to our home page.  Various versions of our logo can be obtained from our _logo page_.

_double space white space_

For publications, please cite SNAP this way:

_indent_ Scenarios Network for Alaska and Arctic Planning (SNAP), University of Alaska, www.snap.uaf.edu, accessed [insert date here]

_double space white space_

The following are concise suggestions to incorporate into various scientific publications being produced at SNAP or with SNAP data. These are meant as a starting point only, and can easily be modified to suit a particular publication.

_indent_ Model Selection

_indent_ SNAP downscaled data is a value added product derived from global climate model (GCM) output. By comparing surface temperature, precipitation, and sea level pressure between observation-based ECMWF 40 Year Re-analysis data (ERA-40) and GCM output variables, the five best performing GCM’s across Alaska and the Arctic were determined to be: cccma_cgcm31, mpi_echam5, gfdl_cm21, had_cm3, and ccsr_miroc32medres (Walsh et al 2008). In addition to this, a five model average output was calculated in order to further reduce the error 

etc

**Comment by brucecrevensten** [comment]
For the FAQs, please change citation text to the below (sorry, we're settling on a format, and this is the one I'm betting we'll settle on, APA style)

Scenarios Network for Alaska and Arctic Planning, University of Alaska. [insert current year]. [insert specific webpage title]. Retrieved [insert date] from [insert URL]

Also, please insert a couple more carriage returns to separate the citation from the text below it.  In other words, the logo inclusion and citation format is more important than the concise suggestions text below it.
