### ISSUE TITLE
Question regarding time distribution on Community Charts tool

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#67]
#### The question:

Hi Scott,

Tried out the community charts today. I like them very much, and recognize at least some of the limitations. 

I have one question: Why does the graph use non-uniform time periods and time gaps between the data groups? i.e., If you number the 5 sets of data 1-5 starting with 1961-90 = 1, there are data gaps of 20, 11, 11 and 21 years between the groups, and groups covering 29, 29, 9,9, 9 years each. And finally, why have the gaps in time at all between groups?

I know there is some very good logic behind this, but I can't see it.

Hope all is well with you. Please say hello to Sarah for me. It was good to see you in the last couple of weeks. Next time I hope to have a new supply of prawns or something else delectable. It would be fun to get you back for dinner when my wife, Kate Troll, is in town.

Thanks,

BH

Bill Hanson
Field Supervisor
USFWS Juneau Field Office
3000 Vintage Blvd., Suite 201
Juneau, AK 99801
907-780-1170
#### Tom's response:

Hi Bill, I think I see what you are getting at.  The gap numbers I calculated are a little different than yours, but here's some reasoning.

Jan - Dec of each year

1961-1990, 2010-2019, 2040-2049, 2060-2069, 2090-2099

1-5 starting with 1961-90 = 1, there are data gaps of 20, 11, 11 and 21 years between the groups, and groups covering 29, 29, 9,9, 9 years each

I get data gaps of 19, 20, 10 and 20 years between the groups, and groups covering 30, 10, 10, 10, 10 years each

1961-1990: "the past" - this is simply a standard 30 year climatological period that is updated every 10 years.  30 years is an artifact of a decision by meteorologists long ago and sticks around today.  This was also the period that our base climate data from PRISM was produced under which was used as baseline climate for our downscaling of the GCM data.  We also have another downscaled product for Alaska only at 771 meter resolution that is based upon the 1971-2000 PRISM data, but is not used in this tool.

2010-2019:  "what's going on now" - simply because this is the current decade we're all living in.

We then wanted to show what the trend was going to be between the current decade and the end of the century, where our data ends.  This left us with the 2020s, 30s, 40, 50, 60, 70s, 80s, and 90s.  Having all those decades on the tool would make the chart too dense and not really provide much more info since these are decadal averages of a 5 model average.  Good for showing general trends, but not really variability.  So we picked the 40s, 60s, and 90s.  Most folks seem to be interested in planning for the next 50 years, so we covered that with the 40's and 60s, but it's always nice to see the distant future as well, hence the 90s.

Of course, there's more than one way to do this.  In the future, it would be nice to allow the user to choose whatever decade they would like to see, but we're not to that point yet.

Thanks for asking.  I never really considered it in that light.

Tom

**Comment by carolynrosner** [comment]
Moved to snap-drupal repo.
