### ISSUE TITLE
Question re: variability in projected precip/temp

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#69]
#### a user asked...

On Wed, May 2, 2012 at 3:58 PM, Laurel Kaminski Laurel.A.Kaminski@us.mwhglobal.com wrote:
Hi Michael / Tom -

I have a question about the projected temperature and precipitation data available on the SNAP website. 

I would like to know if model outputs are based only on deterministic inputs, or is there some variability year to year.  Or, in other words, if I want to know what the general climate will be like 50 years in the future compared to now, is it okay to just use the projections for 2062?  Or is it a better idea to use the average of all the years between, say, 2057 and 2067 to account for year to year variability?

Thanks!
Laurel
#### Tom responded...

On Wed, May 2, 2012 at 4:36 PM, Thomas Kurkowski takurkowski@alaska.edu wrote:
Hi Laurel,

Yes, there is definitely variability in the monthly climate outputs.  If you are interested in general climate trends, or in other words, trends in the mean, utilizing decadal summaries would be ideal.  The variability in monthly or even annual data comes from multiple sources, one of which is simply the natural variability in a climate system.  Other sources include differences in the way different groups model climate and the use and assumption of various future scenarios.

As you've likely realized, we provide monthly data from 5 Global Climate Models, a composite 5 model average (which averages out a lot of the expected variability within a single model), as well as annual, and decadal averages, which can smooth this out even more.  It really depends if you are interested in general trends (change in mean values), or changes in the variability (hot extremes, storm events, etc).

I've Cced Nancy Fresco, who can also answer more specific questions about interpretation of the data.

I'd also like to make you aware that we recently applied a license to all SNAP products.  Commercial users are asked to please contact us first if they would like to use our data.  We can license it out for commercial purposes under a different license.

http://www.snap.uaf.edu/terms.php

Thanks,
Tom

**Comment by carolynrosner** [comment]
We have a modal that addresses something like this issue at https://www.snap.uaf.edu/methods/downscaling -- At #3 on that page, see blue button, "Why did we use a proportional anomaly for precipitation?"

This may link to a larger discussion of the FAQ concept and its usefulness, how to make this stuff findable and usable when it's needed ... too often FAQs end up being "dumping grounds" for info no one has figured out a home for.
