### ISSUE TITLE
Feedback from Sarah re: finding items, link from maps page

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#75]
Hi Everyone,

I've been trying to share some of SNAP's resources with folks and cannot find them on the website...
Are the fact sheets that Lena put together for CES last summer posted?  If so, where?

Also, a few suggestions for improvement:
- from the maps page, it would be nice to have a link back to the home page (the back button doesn't take me anywhere)
- on the "Resources" page it looks like there are presentations posted under Reports..

Is Kristin working on organizing our products so that they are easy to find on the site?  I have to be honest, its not intuitive or easy to find products for an outsider...

Thanks,
Sarah

**Comment by carolynrosner** [comment]
I can't speak to the maps page, but ...  

We no longer have a Resources page or content type. Everything that was there has been migrated to the new site, to a place where most appropriate to the topic of the resource (file, presentation, report..) See this for a trail I left for what moved where:
https://docs.google.com/a/alaska.edu/spreadsheets/d/11Rv6466htQ30R2BvpJmAlbu1s1wGy_ifkF-G1wrDaeU/edit?usp=drive_web

Not sure what is meant by "products" -- does she mean Resources? If we want to post Products, I think a good strategy is to figure out which Expertise area fits best, and keep them there, e.g. CES factsheets are science communication products, I would think.
