### ISSUE TITLE
Add resource / fact sheets 

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#80]
Yes, there were some inaccuracies that were in the original doc, the new ones Lena has produced look good. Bruce, let's put these in for the next round so it gives us time to get you all the requirements (blurbs, titles, etc.)

"SNAP Documents" sounds good to me. These headings will change over time anyways, since we're putting them into categories, things always get messy with time.

From /Shared/SNAP website/Resources

Let's include the below...

ClimateDerivations.pdf
Alaska_Climate_Projections_Statewide.pdf
6 versions of Alaska_Regional_Climate_Projections_xxxx.pdf (I split them up into individual files for more specific downloads)

Let's not include this one yet due to no KML for new data sets currently in existence:
ClimateScenarioTools.pdf

**Comment by takurkowski** [comment]
closing this, since all docs are either on the site now or currently being altered/in review.
